var _selectDescriptions =
{
	"duty": "Get homework done, get to rehearsal on time, being a good friend.",
	"glory": "Winning the game, having the nicest car, having the best grades.",
	"justice": "Animal rights, supporting the underdog, keeping systems fair.",
	"love": "Crushing, soulmates, holding hands, passionate kisses, making out.",
	"power": "Popularity and influence, being the goto guy/gal, looking down on others.",
	"truth": "Classroom smarts, gossip, getting to the bottom of things, solving mysteries.",

	"rich": "You were born with a lot of money (rich family, etc).",
	"ordinary": "You were born into an typical household.",
	"gifted": "You were born with intrinsic talent (music, IQ, literary genius, etc).",
	"strange": "You were born under strange circumstances (commune, foreign culture, future, etc).",
	"metahuman": "You were not born as a human (martian, fairy, monster, god, etc).",

	"jock": "You grew up with an emphasis on athletic ability (lots of sports, gymnastics, etc).",
	"average": "You grew up with a typical emphasis.",
	"geek": "You grew up with an emphasis on intellectual and/or esoterica (professor parents, dungeons and dragons, musical theater, etc).",
	"outsider": "You grew up outside the mainstream culture (poor, bad family reputation, etc).",
	"paragon": "You grew up with an emphasis on a particular set of principles and characteristics (ethical/heroic, power/control, iconoclast, etc).",

	"money": "You have focused much of your time and energy into acquiring wealth.",
	"life": "You have focused much of your time and energy into experiencing all that life has to offer.",
	"status": "You have focused much of your time and energy into building and maintining your status and power.",
	"technology": "You have focused much of your time and energy into exploring and understanding technology.",
	"paranormal": "You have focused much of your time and energy into exploring and understanding paranormal phenomena.",

	"risky": "You've gravitated towards actions that put you into jepardy on some level.",
	"straight and narrow": "You've adhered to the rules and norms of society in word and deed.",
	"lofty": "You've acted towards your highest dreams and ambitions.  Frequently dramatic and grandiose in word and deed.",
	"underground": "You've worked to build and maintiain connects with secretive groups and individuals.",
	"ethical": "You've acted in accordance with what you know is right.  This sometimes puts you at odds with the mainstream.",

	"advancement": "You've gained in position and power.  Perhaps through promotion or substantial achievement or simple luck.",
	"tragedy": "You've had to cope with a terrible loss.  This means pulling yourself together, strengthening social bonds, etc.",
	"power manifestation": "You were a typical human that somehow gained superhuman ability.",
	"first contact": "You came into contact with the paranormal in a way that changed your life.",
	"destiny": "You became aware of your future fate and it is inevitable: heroic, destructive, terminal, etc.",

	"Agile": "You're quick and nimble, able to move your body effortlessly like a dancer or gymnast.",
	"Athletic": "Through bodybuilding and years of team sports, your body has become a well-oiled machine, eager to take on any challenge.",
	"Attractive": "You're the complete package: face, eyes, hair, skin.",
	"Back handed": "You always have a witty comeback.",
	"Big brother": "You like to keep tabs on other people - just in case they do something that requires your help or intervention.",
	"Big hearted": "You're a good soul - honorable and kind.",
	"Clever": "You're quick-witted and cunning, usually coming up with the solution before the question has even been asked.",
	"Connected": "You know people from all walks of life who are willing to help you out in some way.",
	"Cosmopolitan": "You've been outside of Kansas or know enough about other cultures to not seem like a tourist when leaving Smallville, Metropolis, or her surroundings.",
	"Daring": "You sometimes cross the line between brave and foolish, but there's almost nothing you won't try.",
	"Extraterrestrial knowledge": "You know more than any human should know about cultures outside of the blue planet.",
	"Family reputation": "Your family name holds its own demons and vices, as well as the pride and glory that make it recognizable.",
	"Fast talker": "You've lost track of the problems your mouth has caused over the years.",
	"Fixer": "You're called in to fix a problem when no other solution can be found.",
	"Gearhead": "You bleed motor oil and your heart beats like a mechanical piston.",
	"Genius": "You're an intellectual giant.",
	"Guilty": "You've done something terrible that you can't reconcile in your life.",
	"Hacker": "Computer specialists are all well and good, but you can make the technology behind the keyboard dance at your command.",
	"Heroic reputation": "As a hero, your name is right up there with comic book legends like Warrior Angel.",
	"Impulsive": "You seem to lack what some people call better judgment.",
	"In over my head": "You frequently jump into situations past your depth, but you either fail to recognize it or don't really care about the risks; in fact you seem to thrive on the challenge.",
	"Investigator": "You're adept at finding clues and putting the pieces together to find a criminal or solve a case.",
	"Likeable": "Whether it's your looks, your personality, or your lovely smile, people seem to like and trust you.",
	"Manipulative": "You thrive on twisting others to do your bidding or concede your point of view.",
	"Marksman": "With a ranged weapon - bow, gun, or whatever - you can hit nearly any target you can see, provided it's within the weapon's range.",
	"Martial artist": "You've been trained in one or more melee combat disciplines.",
	"Mastermind": "Your talents run to the strategic rather than the tactical.",
	"Military brat": "You grew up in the military, and you still have connections deep in the green ranks, be it family, friends, or even people who owe you from old gambling debts.",
	"Not born yesterday": "You've managed to avoid the failings of other intelligent people.",
	"Observant": "You keep yourself very aware of your surroundings and are prepared for any eventuality.",
	"On a mission": "You have a rather one-track mind and have dedicated your life to one specific task that is all-encompassing.",
	"Right place, right time": "You have the uncanny knack of being where you need to be.",
	"Savage": "You're a monster that should be feared by your foes for the things you're capable of, someone with a feral side that comes out when you're threatened, angry, or betrayed.",
	"Shameless flirt": "You just can't help yourself.",
	"Smartass": "You inevitably end up shooting your mouth off with sarcastic comments.",
	"Sneaky": "You're fantastic at getting in and out without being seen, with equal parts hiding in shadows, moving without making a sound, and natural agility.",
	"Soldier": "Maybe you're an enlisted member of the armed forces and have the skill and experience to show for it.",
	"Vicious": "When you take off the kid gloves, the claws come out.",
	"Wealthy": "You have enough money to buy your way out of nearly any trouble you inevitably get into.",
	"Weapons master": "You've spent years honing your ability to swing an axe, drive home a sword, or brandish a spear.",
	"Willful": "You're probably too stubborn and proud for your own good; you'll act the way you choose despite the better judgment or advice of others.",

	"Heritage: Almeracian": "It's said the scions of the Royal Bloodline of Almerac, a distant planet ruled by Queen Maxima, have access to amazing abilities that rival those of the Kryptonians and Martians.",
	"Heritage: Atlantean": "The vast ocean depths are home to a mysterious people descended from the sunken continent of Atlantis.",
	"Heritage: Cybernetic": "Scientific and technological geniuses like the engineers at LuthorCorp or even the Science Council on Krypton have mastered the ability to graft cybernetic components, nanotech implants, and even kryptonite-powered hearts into living subjects.",
	"Heritage: Kryptonian": "Although Clark Kent's home planet of Krypton was destroyed, its legacy remains.",
	"Heritage: Magical": "There are various and mysterious ways to gain a magician's legacy.",
	"Heritage: Martian": "Survivors of Mars have powers on a near-Kryptonian level.",

	"Absorption": "You can absorb one kind of energy, whether directed at you or at characters in the same scene as you.",
	"Adaptation": "Your body is able to survive in, and in fact may prefer, an environment that's normally hostile or hazardous to others.",
	"Animal control": "You have some form of psychic link with a single species or type of animal.",
	"Astral projection": "You can leave your physical body behind and travel as a psychic entity or ghost.",
	"Blast": "You wield elemental or energy powers and damage your foes in such a way that primitive societies would have called you a god.",
	"Body transformation": "You can change the molecular makeup of your body to change into another element.",
	"Claws": "Through use of long claws, nails, or knives you slash and hack at your foes.",
	"Combustion": "You create explosive charges that can detonate and cause damage commensurate to the size of the bomb.",
	"Comprehension": "You're a savant, able to understand strange languages and decipher impenetrable codes.",
	"Cryokinesis": "You control cold, ice, and all things related.",
	"Density control": "You have the ability to change the space between molecules in your body making you more and less dense.",
	"Dream manipulation": "Entering people's dreams is a tricky thing.",
	"Duplication": "There is more than one of you.",
	"Earth control": "You can control the very ground beneath your feet, bending it to your will.",
	"Electrokinesis": "Electricity is your plaything, whether it's man-made or naturally occurring.",
	"Flight": "You can break the pull of gravity without an aircraft and soar through the skies.",
	"Force field": "You can create a barrier of energy or force.",
	"Gravity control": "You can manipulate the pull of Earth's gravity on yourself or another person or object.",
	"Healing": "You can heal physical or mental trauma inflicted on others, sometimes with just a touch.",
	"Hydrokinesis": "You have complete control over water, ice, and steam, allowing you to create structures like walls or orbs of water as wellas move water as though through telekinesis.",
	"Illusions": "You can create images that others can see and hear and which seem very real.",
	"Insect control": "You can communicate with and control insects, usually of a single type.",
	"Invisibility": "You can disappear from view at will.",
	"Invulnerability": "You can avoid pain and trauma.",
	"Light control": "You can control coherent light, using it to blind or daze or light up a dark room without a flashlight.",
	"Luck": "Things have a tendency to go your way, whether this is a conscious decision or not.",
	"Magnetism": "You can affect not only the massive magnetic powers of the planet, but the minuscule magnetic properties in every piece of metal, allowing you to create walls of metal to defend yourself or perhaps even slow the blood in a human body due to the iron content.",
	"Mind control": "You can control or influence other people's minds without them realizing, although usually you'll find it difficult to make them do things that go against their deepest beliefs.",
	"Paralysis": "You can lock someone in place, making him incapable of moving or doing anything physical.",
	"Plant control": "You can command plant life to grow or wither at will, to wind around your enemies, and to communicate with you as if it were another person.",
	"Poison": "Your touch or scent can destroy the inner workings of the human body.",
	"Possession": "You can inhabit another's body for a short time.",
	"Power leech": "You're the bane of the powered community, existing to either imitate other Abilities or temporarily take them away.",
	"Precognition": "You can see things before they happen - sometimes only seconds before; sometimes far, far ahead.",
	"Pyrokinesis": "Your control over fire and heat allows you to manipulate temperature as well as flame.",
	"Regeneration": "You can heal physical or mental trauma you've been subjected to.",
	"Shadow control": "A creature of shadow, you can create shadows where ther eare none and cause existing shadows to do your bidding.",
	"Shadow walk": "You can dive into shadows or move as a shadow to get from place to place.",
	"Shapeshifting": "You can alter your appearance or shape to imitate other people, creatures, or even inanimate objects.",
	"Sonic blast": "You can let loose a cacophony of noise that could take out a city block.",
	"Stretching": "You can bend and twist to nearly any shape, becoming both like liquid and stretching far beyond human reach.",
	"Super senses": "Your senses are broader and keener than any mortal's senses should be.",
	"Super speed": "You can move so fast you're rarely seen as more than a colored blur.",
	"Super strength": "You're capable of staggering feats of superhuman strength.",
	"Swimming": "You can move through the water at great speeds, more like a dolphin or shark than a human.",
	"Technopathy": "You can control technology remotely with your mind, accessing even unfriendly devices as if they were your home computer.",
	"Telekinesis": "You can levitate and move people, objects, even yourself with your mind.",
	"Telepathy": "You can enter the minds of others, conveying messages or even reading thoughts and memories.",
	"Teleportation": "You can move from one place to another without moving at all.",
	"Time control": "You can bend the flow of time around you, slowing or speeding it up to suit your needs.",
	"Tunneling": "You can dig deep under the ground as fast as a person can walk, allowing you to make tunnel passagesways to and from your destinations.",
	"Wall walking": "You can move up and down walls and across ceilings as easily as walking across your living room floor.",
	"Wind control": "You have the power to control the movement of air, whirling it around or redirecting powerful winds.",
};
